print("Starting test!")
local m1 = require("module1")
local m2 = require("module2")
print("modules imported")
local name = m1.getRandomName()
print("module1's method called")
m2.sayHelloTo(name)
print("module2's method called")
print("finish")